exp:
  dir: logs/DFAFVQA2test2
  resume:  #last #, best_[...], or empty (from scratch)
dataset:
  import: EMuRelPA.datasets.factory
  name: vqa2 
  dir: data/vqa/vqa2
  train_split: train
  eval_split: val # or test
  proc_split: train # or trainval (preprocessing split, must be equal to train_split)
  nb_threads: 4
  batch_size: 256 #1500
  nans: 3000 
  minwcount: 0
  nlp: mcb
  samplingans: True
  dir_rcnn: data/vqa/data/vqa/coco/extract_rcnn/2018-04-27_bottom-up-attention_fixed_36
  vg: False
  dir_vg: data/vqa/vgenome
  dir_rcnn_vg: data/vqa/data/vqa/vgenome/extract_rcnn/2018-04-27_bottom-up-attention_fixed_36
model:
  name: default
  network:
    import: EMuRelPA.models.networks.factory
    name: DFAF
    txt_enc:
      name: skipthoughts
      type: BayesianUniSkip
      dropout: 0.25
      fixed_emb: False
      dir_st: data/skip-thoughts
    output_size: 100 
    output_features: 2400
    question_features: 2400
    vision_features: 2400
    hidden_features: 512
    num_inter_head: 8
    num_intra_head: 8
    num_block: 2
    visual_normalization: True
    max_answers: 3000
    t_emb: False
  criterion:
    import: EMuRelPA.models.criterions.factory
    name: vqa_cross_entropy
  metric:
    import: EMuRelPA.models.metrics.factory
    name: vqa_accuracies
optimizer:
  import: EMuRelPA.optimizers.factory
  name: Adam
  lr: 1.5e-3
  gradual_warmup_steps: [0.5, 2.0, 7.0] #torch.linspace
  lr_decay_epochs: [14, 24, 2] #range
  lr_decay_rate: .1
engine:
  name: logger
  debug: False
  print_freq: 10
  nb_epochs: 100
  saving_criteria:
  - eval_epoch.accuracy_top1:max
misc:
  logs_name:
  cuda: True
  seed: 1337
view:
  name: plotly
  items:
  - logs:train_epoch.loss+logs:eval_epoch.loss
  - logs:train_epoch.accuracy_top1+logs:eval_epoch.accuracy_top1
  - logs_train_oe:train_epoch.overall+logs_val_oe:eval_epoch.overall
